@startuml Sequence
skinparam shadowing false

Benutzer -> Browser: Click: Show statistics
Browser -> Browser: Read Form
Browser -> Server: HTTP Request <URL>
Server -> RandomEvent: GetRandomEvents(...)
RandomEvent -> Database: SELECT * FROM RandomEvents ...
Server --> Browser: HTTP Response
Browser -> Browser: Draw Diagram

@enduml
